### ISSUE TITLE
请问，如何支出IE（Edge）呢？

### ISSUE THREAD

**Issue by ForBurning** [xunleif2e/vue-lazy-component#11]
已经在项目中引入了babel-polyfill, 但是不起作用。 
请问是我引入错误导致的吗？

**Comment by binggg** [comment]
你好，感谢反馈
可能是文档中表达的不太清楚，你需要引入IntersectionObserver polyfill 
我更新了下最新的文档，你可以参考下
https://github.com/xunleif2e/vue-lazy-component#%E6%B3%A8%E6%84%8F--notes

**Comment by ForBurning** [comment]
解决了！ 再次感谢！
