### ISSUE TITLE
华为P20微信小程序中内嵌h5，无法懒加载

### ISSUE THREAD

**Issue by devlee** [xunleif2e/vue-lazy-component#14]
华为P20微信小程序中内嵌h5，无法懒加载，但是在微信浏览器里是可以懒加载的

**Comment by binggg** [comment]
检查下是否支持  IntersectionObserver API

**Comment by devlee** [comment]
使用了IntersectionObserver的polyfill，不知道是不是因为原生不支持，是polyfill的问题

**Comment by binggg** [comment]
可以先看下小程序中内嵌h5本身支不支持IntersectionObserver，再定位是不是polyfilll的问题

**Comment by devlee** [comment]
已反馈微信官方，所以关了
