### ISSUE TITLE
请问，如果内容高度不知道的情况下，有大有小，会出现数据重叠的情况

### ISSUE THREAD

**Issue by xjccc** [xunleif2e/vue-lazy-component#2]
移动端，渲染列表的时候，内容文字很多，会出现数据的重叠，请问有没有好的解决方法，谢谢。

**Comment by binggg** [comment]
是不是这样的情况

假设 懒加载组件 高200px
假设 真实组件 高300px
切换时有可能真实组件叠加到相邻的模块？

**Comment by xjccc** [comment]
是这样的。会占位到相邻模块，闪一下

**Comment by binggg** [comment]
最简单的方式
```
<vue-lazy-component style="overflow: hidden">
  ...
</vue-lazy-component>
```

**Comment by xjccc** [comment]
嗯，重叠是解决了，但是给人的感觉稍微有点怪怪的0 0.谢谢啦

**Comment by binggg** [comment]
好，如果不需要transition效果的话，可以直接把css重写掉，这样就不会出现绝对定位这种了，不过切换回相对生硬些
