### ISSUE TITLE
关于异步组件的问题

### ISSUE THREAD

**Issue by tom-wang** [xunleif2e/vue-lazy-component#3]
1、如果组件比较长，头部漏出一点点，下面的大片内容开始加载，好像不太符合常规的懒加载
2、针对懒加载图片有一个建议是单独实现一个aimg组件，接受跟img一样的属性，但是会做懒加载，这样可以做到真正意义上的懒加载

**Comment by binggg** [comment]
其实粒度是可大可小的，大的可以懒加载一个模块，小的可以懒加载一个图片、iframe等
现在可以在

```html
<vue-lazy-component>
    <img :src="'https://api.adorable.io/avatars/40/'+ userid + '@adorable.png'">
</vue-lazy-component>
```

就可以实现一个图片懒加载

不过你说的实现一个aimg组件也是可以的，可以用vue-lazy-component简单封装下就有了

**Comment by tom-wang** [comment]
感谢解答
