### ISSUE TITLE
 Compatible with a Safari 11.0.2 (13604.4.7.1.3)

### ISSUE THREAD

**Issue by binggg** [xunleif2e/vue-lazy-component#5]

**Comment by sarahxoxo** [comment]
It seems IntersectionObserver function is not support on safari.
Then I import this polyfill plugin and it worked!
[https://github.com/w3c/IntersectionObserver/tree/master/polyfill](https://github.com/w3c/IntersectionObserver/tree/master/polyfill)
For those who need to use this vue-lazy-component on safari.

**Comment by binggg** [comment]
Thanks
