### ISSUE TITLE
Vue 2.5.16 运行出错

### ISSUE THREAD

**Issue by jacobcyl** [xunleif2e/vue-lazy-component#9]
[Vue warn]: Error in mounted hook: "TypeError: window.IntersectionObserver is not a constructor"

found in

---> <VueLazyComponent> at /Users/benzhao/Sites/@xunlei/vue-lazy-component/src/VueLazyComponent.vue
       <IndexContainer> at resources/assets/app/js/containers/IndexContainer.vue
         <App> at resources/assets/app/js/pages/App.vue
           <Root>

**Comment by binggg** [comment]
某些浏览器不支持 IntersectionObserver

可以引入 IntersectionObserver polyfill

https://github.com/w3c/IntersectionObserver/tree/master/polyfill
